### ISSUE TITLE
Klipper and gtr

### ISSUE THREAD

**Issue by shawnp30** [bigtreetech/BIGTREETECH-GTR-V1.0#37]
Has anyone successfully compiled gtr with klipper. I get lost after trying to find mcu. I have followed links to use gnd and tx and rx on the li and gtr.  I have disabled serial and usb as klipper and btt suggested. Still cannot find mcu. My pi and board seem to not be communicating what can I do to get this working.

**Comment by BronsonMMiller** [comment]
Wow what a wonderful and vibrant community GTR has here. Oct 2020 and not one answer to such a simple question? I should just return this funkkin' board to amazon while I still can...

**Comment by dzhaparoff** [comment]
BTT do not care about post sale support... And GTR is not so common used board, community is very small.

**Comment by shawnp30** [comment]
My gtr works just fine. It was an error on my part. Gtr is one of the best boards for buck to use. The fact I can run all my motors for corexy triple z in one board with room for an expansion board works perfectly.
