### ISSUE TITLE
Configure the BTT TFT70 V3.0 firmware v3.0.27

### ISSUE THREAD

**Issue by Decalis1979** [bigtreetech/BIGTREETECH-GTR-V1.0#68]
I have a Geeetech 3 hotend on , in version V3.0.26 the exhausts appeared normal on the screen (E0, E1 and E2). When I upgraded to V3.0.27 they no longer show up. I modified the config.ini putting hotend_count:1 and (Extruder Count) ext_count:3. And I can't move the E1 and E2 extruders because they don't appear to select on the screen.

**Comment by radek8** [comment]
Your question is in the wrong repository.
Questions about FW TFT can be found here:
https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues

If you have a mixing extruder, try to set it in the FW TFT display in the Configuration.h file
#define MIXING_EXTRUDER 1

Then compile your own FW and upload it to the display.
